create quiz flux
GuiOdes/ferramenta-quiz pull request #5
Opened 2024-10-31 04:43 UTC by alexandrendev

2024-10-31 04:46 UTC, alexandrendev commented
Conflito na classe UserRepository resolvido

2024-11-03 01:45 UTC, GuiOdes requested changes

2024-11-03 01:45 UTC, GuiOdes commented on src/main/kotlin/com/sistemas/ferramentaquiz/api/controller/QuizController.kt
> +    @PostMapping("")
```suggestion
    @PostMapping
```

Não precisa colocar parâmetro se não for colocar uma URI especifica

2024-11-03 01:45 UTC, GuiOdes commented on src/main/kotlin/com/sistemas/ferramentaquiz/api/request/CreateQuizRequest.kt
> +    val code: String? = null
Creio que a gente n precise disso aqui. Nós podemos gerar sempre os códigos pra manter o controle disso na aplicação

2024-11-03 01:45 UTC, GuiOdes commented on src/main/kotlin/com/sistemas/ferramentaquiz/service/QuizService.kt
> +    fun generateAcessCode(): String {
Será que não rola a gente usar uma lib pra isso? Tipo essa aqui: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html

2024-11-03 15:08 UTC, alexandrendev commented on src/main/kotlin/com/sistemas/ferramentaquiz/service/QuizService.kt
> +    fun generateAcessCode(): String {
Opa.
Beleza, vou dar uma olhada hoje.

2024-11-03 15:09 UTC, alexandrendev commented on src/main/kotlin/com/sistemas/ferramentaquiz/api/request/CreateQuizRequest.kt
> +    val code: String? = null
Beleza
Só a parte do code ne?

2024-11-03 15:18 UTC, GuiOdes commented on src/main/kotlin/com/sistemas/ferramentaquiz/api/request/CreateQuizRequest.kt
> +    val code: String? = null
Isso. O title pode manter

2024-11-03 19:36 UTC, GuiOdes requested changes

2024-11-03 19:36 UTC, GuiOdes commented on src/main/kotlin/com/sistemas/ferramentaquiz/dto/CreateQuizDto.kt
> +data class CreateQuizDto(
Pq não poderia ser um QuizDto?

2024-11-04 12:30 UTC, merged